services:
  layout-menu-editor:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: layout-menu-editor
    restart: unless-stopped
    expose:
      - "8080"
    networks:
      - npm_local

networks:
  npm_local:
    external: true
